### ISSUE TITLE
Avoid requiring editable builds (`-e`) for running tests

### ISSUE THREAD

**Issue by leofang** [NVIDIA/cuda-python#108]
Right now it is quite subtle that the test/benchmark suites are designed to only allow editable builds to run. For normal builds, pytest has a hard time importing the needed modules. I stumbled over this for a few times.
https://github.com/NVIDIA/cuda-python/blob/e1e332564c48db556212d59262a149b1a63285e8/docs_src/source/install.md?plain=1#L65
This should be fixed.

**Comment by leofang** [comment]
Not sure if this is related, but instead of the current layout for tests/examples/benchmarks
- cuda/setup.py
- cuda/cuda/bindings/tests
- cuda/cuda/bindings/examples
- cuda/cuda/bindings/benchmarks

ideally the layout should have been made such that they are outside of source tree and living side-by-side with `setup.py` for the package, so
- cuda/setup.py 
- cuda/cuda/bindings/
- cuda/tests
- cuda/examples
- cuda/benchmarks

I probably made a bad mistake back then (leofang/cuda-python#1) 😓 

cc @vzhurba01

**Comment by vzhurba01** [comment]
Resolved by MR https://github.com/NVIDIA/cuda-python/pull/159. Updated [cuda-python/cuda/README.md](https://github.com/NVIDIA/cuda-python/blob/main/cuda_bindings/README.md#testing) with how to run.

The final commands are:
Command to test against in-tree builds:

- unittests: `cuda-python/cuda_bindings$ python -m pytest tests/`
- samples: `cuda-python/cuda_bindings$ python -m pytest examples/`

Command to test against distributable package (wheels/conda)

- unittests: `cuda-python/cuda_bindings$ pytest tests/`
- samples: `cuda-python/cuda_bindings$ pytest examples/`

Closing.
