### ISSUE TITLE
CI Test failure: ImportError: cannot import name 'cuda' from 'cuda'

### ISSUE THREAD

**Issue by sandeepd-nv** [NVIDIA/cuda-python#128]
See: https://github.com/NVIDIA/cuda-python/actions/runs/10995349507/job/30526001196#step:6:263

**Comment by leofang** [comment]
Many thanks, @sandeepd-nv! 

@vzhurba01 can correct me but I think if we're testing this way (via install a pre-built wheel) we are blocked by #108.

**Comment by leofang** [comment]
Hi @sandeepd-nv, unfortunately my wording above ("... blocked by ...") was misleading and I dropped the ball. @m3vaz raised this to me in the sync-up today, and I explained: 
- Before we fix #108 let's do **editable** installation in the CI, then we can run the tests
- After we fix #108, let's do it the right way as if we are end users (build a wheel first, and then install the wheel)

Let me know if you have any question, thanks!

**Comment by m3vaz** [comment]
Thanks @leofang for the clarification, I'll drive this forward with @sandeepd-nv

**Comment by leofang** [comment]
With the last piece merged https://github.com/NVIDIA/cuda-python/pull/252 this should no longer be an issue.
