### ISSUE TITLE
Explain the layout change in the release note

### ISSUE THREAD

**Issue by leofang** [NVIDIA/cuda-python#145]
Right now the entry in our release note is unclear what's changed:
https://github.com/NVIDIA/cuda-python/blob/797286bb003e0ab9905e7659f85e8cc7b376ee42/docs_src/source/release/12.6.1-notes.md?plain=1#L6
and it could be confusing because all API references now point to the new layouts only, partly because of the Sphinx limitations (#140).

We should:
- Reuse text from #75 to teach about old vs new locations (ex: `cuda.cuda` vs `cuda.bindings.driver`)
- Emphasize the old paths are still working and this is a bc change

**Comment by vzhurba01** [comment]
Resolved by MR https://github.com/NVIDIA/cuda-python/pull/159. Closing.
