### ISSUE TITLE
Documented return types in cudart.pyx are inconsistent with implementation.

### ISSUE THREAD

**Issue by bdice** [NVIDIA/cuda-python#15]
The function signature of many APIs in the docs appear to return a 2-tuple like `(status, None)` but the actual return value is a 1-tuple like `(status,)`.

For example:
Docs link: https://nvidia.github.io/cuda-python/api.html#cuda.cudart.cudaSetDevice
Source: https://github.com/NVIDIA/cuda-python/blob/d7a354dc994cfccc2b1be536e760789605f4e571/cuda/cudart.pyx#L7903-L7910
Rendered docs: ![image](https://user-images.githubusercontent.com/3943761/144930508-37548475-5220-4873-a89f-d6e3557eacb1.png)

In some cases, there is a second element like a string or memory pool in the tuple but the documented type indicates it as `None`.

For example:
https://github.com/NVIDIA/cuda-python/blob/d7a354dc994cfccc2b1be536e760789605f4e571/cuda/cudart.pyx#L7164-L7193
https://github.com/NVIDIA/cuda-python/blob/d7a354dc994cfccc2b1be536e760789605f4e571/cuda/cudart.pyx#L7641-L7670

~Let me know if you'd like me to work on this issue. I would be happy to contribute a pull request to improve the docs. 👍~ I see PRs are not currently accepted.

**Comment by vzhurba01** [comment]
Thanks for the notice! Fix submitted.

**Comment by bdice** [comment]
Thank you @vzhurba01! 😊
