### ISSUE TITLE
`cuda.core`: Bump version to 0.1.0

### ISSUE THREAD

**Issue by leofang** [NVIDIA/cuda-python#170]
Two places
- https://github.com/NVIDIA/cuda-python/blob/main/cuda_core/cuda/core/_version.py
- https://github.com/NVIDIA/cuda-python/blob/main/cuda_core/docs/versions.json

**Comment by vzhurba01** [comment]
Blocked on PR https://github.com/NVIDIA/cuda-python/pull/165. As soon as it's submitted I can updated both places together.
