### ISSUE TITLE
Missing docs for cudaStreamCreateWithFlags

### ISSUE THREAD

**Issue by jrwaine** [NVIDIA/cuda-python#21]
On the API reference, there is no documentation about `cudaStreamCreateWithFlags`, despite other streams functions mentioning it (as [here](https://nvidia.github.io/cuda-python/module/cuda.html#cuda.cuda.cuStreamCreate)). 

Also, it was not clear for me how to specify flags in stream, for example, what is the value or where can I find `CU_STREAM_DEFAULT` or `CU_STREAM_NON_BLOCKING`. 

I'm looking forward to migrate from pycuda to cuda-python, great to see this effort!

**Comment by jakirkham** [comment]
Maybe [this]( https://nvidia.github.io/cuda-python/module/cudart.html#cuda.cudart.cudaStreamCreateWithFlags ) is helpful?

That said, can see in the "See also" section not all of the functions get cross-referenced.

**Comment by vzhurba01** [comment]
With release of CUDA Python 11.7.0 the docs have been refactored. The cross-module linkage (as well as in-module) has been added.

A couple of additional improvements:
- Docs using bullet points / code / tables are cleaner
- Defines and Enums docs are added (only if exists in C docs)

Closing.
