### ISSUE TITLE
Program tries to create an ObjectCode with an unsupported code type "ltoir"

### ISSUE THREAD

**Issue by vzhurba01** [NVIDIA/cuda-python#212]
Program supports types: ptx, cubin, ltoir
ObjectCode supports types: ptx, cubin, fatbin

When a `Program` is compiled with `.compile()`, it creates an `ObjectCode` with the same type but `ltoir` isn't one of the supported types.

**Comment by ksimpson-work** [comment]
I am hitting this while building out and testing the linker object. I have fixed it locally, but need to make sure everything works together before merging anything.

**Comment by ksimpson-work** [comment]
https://github.com/NVIDIA/cuda-python/pull/224

**Comment by leofang** [comment]
Q: I might have missed something, is this resolved? By #224?

**Comment by ksimpson-work** [comment]
No you're right. I was using "closes" instead of keyword "close" in the PR
