### ISSUE TITLE
Get rid of `versioneer` from cuda-bindings

### ISSUE THREAD

**Issue by leofang** [NVIDIA/cuda-python#233]
Offline discussions with @vyars @bryevdv suggests that any of those tools listed [here](https://setuptools-git-versioning.readthedocs.io/en/stable/comparison.html) could be a good alternative.

Alternatively, we can just manually bump `__version__` in `_version.py`, as done in `cuda.core`, and let it propagate to other places (ex: `pyproject.toml`).

`versioneer` has the following disadvantages 
- add an extra build-time dependency (to calculate the version)
- the version scheme is nonsense for local development
- no way to decouple release versions from git tags 
   - confirmed with @vzhurba01 it is fundamentally unfriendly with our release process (that QA could discover bugs after tagging), meaning we tag first, build wheels, if there are bugs caught by QA then we fix the code, **revoke the old tag, and re-tag the same tag** at the latest commit (with the fixes included)
   - the highlighted part is the most problematic if not also confusing

**Comment by leofang** [comment]
Bumping this to P0 as this would prevent the `cuda-binidngs` wheels generated in the CI from being reusable, as the git tag would be included as part of the version tag, and we can't update the git tags casually. @vzhurba01 please prioritize for this, thanks.

**Comment by bdice** [comment]
Removing versioneer should also help fix this issue I saw in conda-forge packages:

```
$ conda install -c conda-forge cuda-python
$ conda list | grep cuda-python
cuda-python               12.6.2          py312he9d8a76_1    conda-forge
$ python -c "import cuda.bindings; print(cuda.bindings.__version__)"
0+untagged.302.g4a12ae2.dirty
```

I discussed with @vzhurba01 and it seems this is occurring because no git tags are present in the source tarballs used to build conda-forge packages.
