### ISSUE TITLE
Cython tests need build instructions

### ISSUE THREAD

**Issue by vzhurba01** [NVIDIA/cuda-python#244]
Currently the Cython tests are segregated to test_cython and there are no instructions on how to build them.
Should we have a setup.py? Can we avoid it with a simply cythonize + command approach?

Need updates to README for how to build them and use them.
Also, would it be better to have a folder layout such that we have:
- `cuda_bindings/tests/python/*` for Python tests
- `cuda_bindings/tests/cython/*` for Cython tests

**Comment by leofang** [comment]
> Can we avoid it with a simply cythonize + command approach?

Yes I think so. I like doing things in a simple & easy-to-maintain way even if it might seem "silly", and this is one such case. We can just make Cython a test requirement (gcc/msvc are needed too, but we can't list them in `requirements.txt` or `pyproject.toml`...) and we can call `cythonize()` in a subprocess, similar to what we do in conda-forge.
https://github.com/conda-forge/cuda-python-feedstock/blob/4a12ae297e8ebf4784269fb8daa89a4d0a0a417f/recipe/meta.yaml#L95-L98

**Comment by leofang** [comment]
We also need the CUDA headers of the same major.minor as test dependencies.
