### ISSUE TITLE
Extend github.io documentation with nvJitLink API references

### ISSUE THREAD

**Issue by vzhurba01** [NVIDIA/cuda-python#251]
>https://nvidia.github.io/cuda-python/cuda-bindings/latest/api.html

We have documentation for the Driver, Runtime and NVRTC APIs, but none of nvJitLink. It should be added.

**Comment by leofang** [comment]
Indeed we should have it. For clarification I meant to have nvJitLink bindings exposed in the next regular CUDA Python release (I just set the milestone); the fact that it went out early due to the hot fixes was a (happy?) accident. It's not fully vetted by QA so we should keep it stealth as is.

**Comment by leofang** [comment]
(btw we also need a release note entry on this when we add the docs)
