### ISSUE TITLE
CI: Add a glibc symbol test as part of our per-PR tests

### ISSUE THREAD

**Issue by leofang** [NVIDIA/cuda-python#295]
xref: https://github.com/conda-forge/cudnn-feedstock/pull/97

We already use `auditwheel repair` when building our wheels, so maybe this is redundant. Setting this to P2 for now.

**Comment by leofang** [comment]
@carterbox WDYT?

**Comment by carterbox** [comment]
I think it's good to either explicitly check glibc symbols or ensure that all of your build containers are using your oldest supported glibc and to know what that oldest supported version is.

It looks like `auditwheel show` is the one that does the glibc ABI checking.

**Comment by leofang** [comment]
> or ensure that all of your build containers are using your oldest supported glibc and to know what that oldest supported version is.

Yeah we use `cibuildwheel` in the GHA to build wheels, and on Linux it does use the manylinux containers:
https://cibuildwheel.pypa.io/en/stable/options/#configuration-file
so my feeling is we don't have to do anything extra.
