### ISSUE TITLE
First base of 'CUkernelNodeAttrValue_v1' is not an extension type

### ISSUE THREAD

**Issue by bertmaher** [NVIDIA/cuda-python#30]
I'm trying to compile cuda-python in a fairly minimal conda environment (nothing installed but the requirements), with cuda-11.6 installed, and seeing several instances of the following sort of error:
```
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              Get memory address of class instance

          """
          pass

      cdef class CUkernelNodeAttrValue_v1(CUlaunchAttributeValue_union):
                                         ^
      ------------------------------------------------------------

      cuda/cuda.pxd:2637:36: First base of 'CUkernelNodeAttrValue_v1' is not an extension type
```

I do have other cuda versions installed alongside 11.6 but judging from the output of `Parsing headers in "/usr/local/cuda-11.6/include" ` it seems like it's probably finding the right version?  Any advice on how to get past this, or debug it?  Thanks!

**Comment by vzhurba01** [comment]
>https://nvidia.github.io/cuda-python/release/11.8.0-notes.html#source-builds
>and
>Issue https://github.com/NVIDIA/cuda-python/issues/22

In 11.7.1, a new requirement to source builds was added where the latest CTK must be used. The above links talk about it in further detail.
I see that only the release notes mention this (but neither README.md nor install page) since that release, I'll keep this issue open until they're both updated.

**Comment by vzhurba01** [comment]
Release [v11.8.1](https://github.com/NVIDIA/cuda-python/releases/tag/v11.8.1) updates both README.md and install page.

Closing.
