### ISSUE TITLE
PyCuda Error: The context stack was not empty upon module cleanup. (When running cron)

### ISSUE THREAD

**Issue by WackyHaker** [NVIDIA/cuda-python#31]
Hi, I am running into the ''Context stack was not empty" error when I try to run a computer vision script on a webcam with a gstream pipeline. It works fine when running it from the terminal but when I schedule it with corn it runs into this error. Any suggestions?

**Comment by vzhurba01** [comment]
I think you're looking for folks over at https://github.com/inducer/pycuda. Cheers.
