### ISSUE TITLE
install IT in jetson agx xavier

### ISSUE THREAD

**Issue by Fischer-pixel** [NVIDIA/cuda-python#33]
could you please update the readme about how to compile it in jetson agx xavier?

**Comment by vzhurba01** [comment]
From v11.8.1 the compile instructions in `README.md` now points to the docs [Installing from Source](https://nvidia.github.io/cuda-python/install.html#installing-from-source).

The steps are essentially:
1. Install CUDA Toolkit
2. Install [requirements](https://github.com/NVIDIA/cuda-python/blob/main/requirements.txt)
3. Set environment variable `$CUDA_HOME`
4. Run `pip install .`

This should work on jetson agx xavier as well.
