### ISSUE TITLE
Ensure all cuda core documentation is in Sphinx style

### ISSUE THREAD

**Issue by ksimpson-work** [NVIDIA/cuda-python#335]
There is some documentation inconsistencies such as StreamOptions:

```python
"""Customizable :obj:`~_stream.Stream` options.

    Attributes
    ----------
    nonblocking : bool, optional
        Stream does not synchronize with the NULL stream. (Default to True)
    priority : int, optional
        Stream priority where lower number represents a
        higher priority. (Default to lowest priority)

    """
```
which should follow the sphinx guidelines. Fom the examples:

```python
class ExampleError(Exception):
    """Exceptions are documented in the same way as classes.

    The __init__ method may be documented in either the class level
    docstring, or as a docstring on the __init__ method itself.

    Either form is acceptable, but the two should not be mixed. Choose one
    convention to document the __init__ method and be consistent with it.

    Note:
        Do not include the `self` parameter in the ``Args`` section.

    Args:
        msg (str): Human readable string describing the exception.
        code (:obj:`int`, optional): Error code.

    Attributes:
        msg (str): Human readable string describing the exception.
        code (int): Exception error code.

    """
```

We should rectify all the documentation to fit this style.

**Comment by leofang** [comment]
We use the NumPy style not the Google style, xref: https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

**Comment by leofang** [comment]
Sorry I probably should have expanded my comment for clarity. The NumPy style has subsection titles followed by a dashed line in the next line, and argument types followed after the arg names, whereas the quoted `ExampleError` docstring is in the Google style, which has subsection titles followed by a colon, and argument types enclosed in parentheses.

I think we should just omit writing argument types in the docstring, and let Sphinx pick them up from the type annotation. But it's a separate task.

**Comment by ksimpson-work** [comment]
My bad, I see. Modified the description
