### ISSUE TITLE
Add support for Python 3.11

### ISSUE THREAD

**Issue by vzhurba01** [NVIDIA/cuda-python#41]
As per [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html), CUDA Python should support Python 3.11.

**Comment by kanisimoff** [comment]
Good day, 

I have the same problem, I can't install cuda-python for python 3.11

Log:
(env) PS D:\nn> py --version
Python 3.11.1
(env) PS D:\nn> pip install cuda-python
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement cuda-python (from versions: none)
ERROR: No matching distribution found for cuda-python

**Comment by vzhurba01** [comment]
Release [v12.1.0](https://github.com/NVIDIA/cuda-python/releases/tag/v12.1.0) adds Python 3.11 support for both Wheels and Conda. Closing.
