### ISSUE TITLE
Exploring CUDA-Aware MPI Transmission in cuda-python

### ISSUE THREAD

**Issue by Ed4everU** [NVIDIA/cuda-python#50]
Hi Developers,

As a newcomer to cuda-python, I'm eager to learn how to implement CUDA-aware MPI transmission. I'd appreciate any guidance or resources on this topic. Thank you!

**Comment by leofang** [comment]
mpi4py already supports this since v3.1.0, I am not sure how it is relevant for CUDA Python? CUDA Python is unaware of MPI and it shouldn't be.

**Comment by Ed4everU** [comment]
Ah, I believe I understand now. So, if I allocate the objects on the CUDA device and transmit them using MPI, the mpi4py library will automatically handle the device-to-device transmission, isn't it?

**Comment by Ed4everU** [comment]
Thank you so much for your informative answer. I see it clearly now. 😁
