### ISSUE TITLE
No wheels for Python 3.11 & 3.12

### ISSUE THREAD

**Issue by fjwillemsen** [NVIDIA/cuda-python#56]
On PyPI, there are no wheels for Python 3.11 and 3.12 for versions under cuda-python 12, despite the fact that these are [both stable versions](https://devguide.python.org/versions/). Python 3.12 wheels are not available on any versions. 
Could wheels for Python 3.11 and 3.12 please be added for the current (11.8.3 and 12.3.0) and all future releases?

**Comment by vzhurba01** [comment]
>https://pypi.org/project/cuda-python/11.8.3/#files
Pypi now has Python 3.11 and 3.12 wheels.

>https://nvidia.github.io/cuda-python/release/12.4.0-notes.html
With the release of CUDA Python 12.4.0 we extended support for Python up to 3.12.

>Could wheels for Python 3.11 and 3.12 please be added for the current (11.8.3 and 12.3.0) and all future releases?
Yes, for the 11.8.x branch we'll support latest Python version as they become available. Likewise for the latest and future 12.x releases.
