### ISSUE TITLE
Build issues with cuda-python 12.3.0

### ISSUE THREAD

**Issue by jakirkham** [NVIDIA/cuda-python#57]
We are seeing build issues with `cuda-python` version `12.3.0` in conda-forge. Here is a snippet taken [from CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=866185&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=779a0c34-7b19-5ccb-5da7-fe4579c91392 ):

```python
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/cuda-python_1706498566763/work/setup.py", line 245, in <module>
    version=versioneer.get_version(),
  File "/home/conda/feedstock_root/build_artifacts/cuda-python_1706498566763/work/versioneer.py", line 1800, in get_version
    return get_versions()["version"]
  File "/home/conda/feedstock_root/build_artifacts/cuda-python_1706498566763/work/versioneer.py", line 1732, in get_versions
    cfg = get_config_from_root(root)
  File "/home/conda/feedstock_root/build_artifacts/cuda-python_1706498566763/work/versioneer.py", line 394, in get_config_from_root
    with open(setup_cfg) as cfg_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conda/feedstock_root/build_artifacts/cuda-python_1706498566763/work/setup.cfg'
```

It looks like `versioneer` is being relied upon to set the version. However `versioneer` expects to find `setup.cfg`, which is no longer in the repo. Looks like [this was dropped as part of the 12.3 upgrade]( https://github.com/NVIDIA/cuda-python/commit/2f9d31cfacc818da0cd4569dd47ea43c5724d2a0#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52 )

**Comment by jakirkham** [comment]
On further inspection see that [`pyproject.toml` was added in 12.3]( https://github.com/NVIDIA/cuda-python/commit/2f9d31cfacc818da0cd4569dd47ea43c5724d2a0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711 ). It appears to configured to use [`setuptools-scm` (a different versioning library)]( https://github.com/NVIDIA/cuda-python/blob/dfd31fa609b9c81bcff925824f38531ab3c96706/pyproject.toml#L10 ) instead

Am a little unclear on whether `setuptools-scm` or `versioneer` are intended to be used here. If the former, the `versioneer` bits would need to be removed and replaced [by what `setuptools-scm` needs]( https://setuptools-scm.readthedocs.io/en/stable/usage/ ). If the latter, `versioneer` would need [an upgrade using a `--no-vendor` install]( https://github.com/python-versioneer/python-versioneer/blob/0.29/INSTALL.md#installation-instructions ) (potentially with some cleanup after)

In either case the current configuration appears to have some issues that need correction. Exactly how to do that would depend on which approach (`setuptools-scm` or `versioneer`) is preferred

**Comment by jakirkham** [comment]
Workaround suggested by Vlad offline is to add `tomli` as a build dependency for Python pre-3.11, which works

Discussing with Vlad offline on how to address more generally

**Comment by vzhurba01** [comment]
Cleaned up versioneer usage with the latest CUDA Python 12.4.0 release. Closing.
