### ISSUE TITLE
Cannot find python package on Jetson Nano (aarch64)

### ISSUE THREAD

**Issue by another-tee** [NVIDIA/cuda-python#59]
I need to install cuda-python (I try via pip install cuda-python) on Jetson Nano,

![image](https://github.com/NVIDIA/cuda-python/assets/118554609/345da5cf-bc7a-4c26-a065-7e1bf2287cfa)

So, I decided to install by pip install cuda_python-12.4.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl

![image](https://github.com/NVIDIA/cuda-python/assets/118554609/a6047ba8-1a12-4d76-af01-a689ce612f40)

I guess, This error occurs because of the python version (my python version is 3.6.9 on ubuntu 18.04)
Please help.

**Comment by vzhurba01** [comment]
>https://github.com/NVIDIA/cuda-python?tab=readme-ov-file#supported-python-versions
Looks like your Python version is on the older side as we currently support Python 3.9 to 3.12. When you switch to one of these more recent versions the error should go away.

Note that per [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html), python 3.6 has been dropped by the community on Jun 23, 2020.
