### ISSUE TITLE
The tutorial in Overview page shows unexpected error

### ISSUE THREAD

**Issue by leofang** [NVIDIA/cuda-python#65]
See below. My guess is during doc build an error was raised when processing the code block.
![截圖 2024-06-11 上午9 45 30](https://github.com/NVIDIA/cuda-python/assets/5534781/45b7bee4-faa3-4162-b4ff-548b5f7acb6b)

**Comment by leofang** [comment]
@vzhurba01 could you take a look when you get a chance?

**Comment by vzhurba01** [comment]
The samples on these pages get automatically ran for validation when the doc is built. The tutorial here had assumed a compute capability that didn't match the local device.

The overview page is now updated to query for the correct compute capability, and tutorial explanations are updated to reflect this.

**Comment by leofang** [comment]
Thanks, @vzhurba01! However, a new error appears as shown below. Is it because we're building the docs in the public, which does not have any GPU support (the error happens as early as `cuInit(0)`)?

![截圖 2024-07-03 下午11 24 32](https://github.com/NVIDIA/cuda-python/assets/5534781/c4ddd8ce-d04c-4b11-81e5-26bd0b6115c2)

**Comment by vzhurba01** [comment]
That would be my mistake. My local device required a workaround that was missed during my build. I've updated my own script so hopefully this issue shouldn't show up on future doc updates.

Overall the docs are build locally, and the uploaded version of [cuda-python/docs](https://github.com/NVIDIA/cuda-python/tree/main/docs) gets used as is.
