### ISSUE TITLE
getLocalRuntimeVersion return val wrong when exisit different version of cuda lib

### ISSUE THREAD

**Issue by MARD1NO** [NVIDIA/cuda-python#67]
When I use cuda-python getLocalRuntimeVersion(), it do not return the correct value. 

I write a simple cpp: 
```
#include "cuda_runtime.h"
#include "stdio.h"

int main() {
    int x; 
    cudaRuntimeGetVersion(&x); 

    printf("x is: %d. \n", static_cast<int32_t>(x)); 
}
```
it returns the correct version 12040, but getLocalRuntimeVersion() returns 12030. 

I have cuda12.3 and cuda12.4, use PATH to assign which cuda I use, How can I solve the problem?

**Comment by leofang** [comment]
You also need to update LD_LIBRARY_PATH if you're on Linux and manage your own CUDA installation instead of relying on the system package manager. `getLocalRuntimeVersion` was designed to always load libcudart from the library search path and return the loaded version.
