### ISSUE TITLE
[EPIC] Python Object Model for CUDA

### ISSUE THREAD

**Issue by jollylili** [NVIDIA/cuda-python#70]
Pythonic CUDA object model.

**Comment by jollylili** [comment]
- [ ] Design/prototype
- [ ]  Development
- [ ]  QA testing
- [ ]  Posting

**Comment by jollylili** [comment]
For the end of Sep 2024 EA, scope includes: Streams, Events, Device,Context, Kernel Launch / Cache, Compiler, Arrays, Spans and Memory Views.

**Comment by leofang** [comment]
The main theme is concluded. All subsequent tasks are already tracked in respective issues. Closing.
