### ISSUE TITLE
cuda.py design stage

### ISSUE THREAD

**Issue by jollylili** [NVIDIA/cuda-python#76]
Objects to cover:
- Device
- Context
- Stream
- Event
- `MemoryResource`
- `Buffer`
- `@viewable` and `GPUMemoryView`
- `launch()` and `LaunchConfig`
- `Program` and `Linker`
- header and DSO search utilities (#62)

**Comment by leofang** [comment]
(updated the issue description)

**Comment by leofang** [comment]
Basic skeleton is laid out in the (internal) design doc and implemented in #87. The design finalization will be an iterative process as we proceed with more beta releases, with multiple (internal) design review meetings and a final sign-off, but the groundwork for a beta 1 release is considered done.
