### ISSUE TITLE
Set up a public, GitHub-Action-based CI infrastructure

### ISSUE THREAD

**Issue by leofang** [NVIDIA/cuda-python#81]
OS/Archs:
```[tasklist]
### Tasks
- [x] linux-64, 1 GPU
- [x] linux-aarch64, 1 GPU
- [x] win-64, 1 GPU
- [x] linux-64, 2 GPUs
- [ ] linux-aarch64, 2 GPUs
- [ ] win-64, 2 GPUs
```
Requirements ("public test matrix"):
- Python: 3.9, 3.10, 3.11, 3.12
- CUDA driver version: 11 & 12
- CUDA Toolkit version: 11.8 & 12.3+

**Comment by m3vaz** [comment]
The linux-64 1xGPU config we should be able to start with, the rest we'll either need to share capacity from other pools or otherwise rack and stack.

**Comment by sandeepd-nv** [comment]
Please review initial set of changes here: #83 and #84.

**Comment by leofang** [comment]
The first four tasks are done (single-GPU CI for all supported platforms + multi-GPU CI for linux-64), see #267 (build) & #124 (test). The remaining two tasks are currently blocked by lack of multi-GPU runners for linux-aarch64 / win-64 (cc: @ajschmidt8 @m3vaz for vis). Let's mark this task as done and track the remaining CI improvements separately.
