### ISSUE TITLE
Add cudaMemcpyToSymbol

### ISSUE THREAD

**Issue by t-vi** [NVIDIA/cuda-python#85]
Hi and thank you for Cuda-Python,

I would like to use constant memory with cuda-python.
I see the symbol functions are listed as not supported in the release notes, but I wonder if they could be added easily.

Best regards

Thomas

**Comment by leofang** [comment]
@vzhurba01 had explained the issue to me long time ago, but I don't recall the technical hurdle off top of my head. May I ask how to you plan to use this API?

**Comment by vzhurba01** [comment]
>https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#symbol-addresses

Workflows involving symbols doesn't align well with our binding strategy. Recall that the C version of CUDA Runtime allows users to declare both their kernels and device-side symbols as part of their `.cu` source file. For CUDA Python to allow the same, we'd need to support writing kernels/symbols using Python. This would need a specialized compiler to make the needed translations, and the integration of it all would drastically raise the scope of these bindings.

Instead, I recommend leveraging the NVRTC bindings as they allow you to both write kernels and global-scope device variables. This would enable equivalent functionality to the unsupported Symbol APIs.

**Comment by t-vi** [comment]
I wanted to use `__constant__` memory with nvrtc.

**Comment by leofang** [comment]
@t-vi If you're an NVRTC user, you should just use `cuModuleGetGlobal`, as Vlad alluded to above, to get the address of a constant memory symbol from a `CUmodule`. This is well supported and, e.g., CuPy does it too:
https://docs.cupy.dev/en/stable/reference/generated/cupy.RawModule.html#cupy.RawModule.get_global
so there's no need in using `cudaMemcpyToSymbol`.
