### ISSUE TITLE
`cuda.cudart.getLocalRuntimeVersion()` raises `RuntimeError: Failed to dlopen libcudart.so.12`

### ISSUE THREAD

**Issue by Matt711** [NVIDIA/cuda-python#89]
Is this a bug? `getLocalRuntimeVersion()` fails for me in cuda 11.8 environment. I'm asking because I see that the API call is in the [cuda-python 11.8 release notes](https://nvidia.github.io/cuda-python/release/11.8.3-notes.html).

In the source code, we're hard coding [`libcudart.so.12`](https://github.com/NVIDIA/cuda-python/blob/e1e332564c48db556212d59262a149b1a63285e8/cuda/_lib/ccudart/ccudart.pyx.in#L4882). Is that right?

Repro
```python
In [1]: from cuda import cudart

In [2]: cudart.getLocalRuntimeVersion()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[2], line 1
----> 1 cudart.getLocalRuntimeVersion()

File ~/.conda/envs/rapids/lib/python3.11/site-packages/cuda/cudart.pyx:24961, in cuda.cudart.getLocalRuntimeVersion()

File ~/.conda/envs/rapids/lib/python3.11/site-packages/cuda/ccudart.pyx:2365, in cuda.ccudart.getLocalRuntimeVersion()

File ~/.conda/envs/rapids/lib/python3.11/site-packages/cuda/_lib/ccudart/ccudart.pyx:2121, in cuda._lib.ccudart.ccudart._getLocalRuntimeVersion()

RuntimeError: Failed to dlopen libcudart.so.12
```

**Comment by Matt711** [comment]
xref [rmm/1675](https://github.com/rapidsai/rmm/pull/1675)

**Comment by leofang** [comment]
It seems to be a backport mistake that we should fix: 
https://github.com/NVIDIA/cuda-python/blob/64cc9ae081ba405972b0472cd1fd35b919c455fc/cuda/_lib/ccudart/ccudart.pyx.in#L2451-L2457
@Matt711 how urgent is this?

**Comment by Matt711** [comment]
> [@Matt711](https://github.com/Matt711) how urgent is this?

Not urgent. We already have a workaround using `numba.cuda`. I also don't mind working on this @leofang, if you could point me in the right direction.

**Comment by leofang** [comment]
Thanks, @Matt711. The offending code that I linked to above is from the [11.8.x branch](https://github.com/NVIDIA/cuda-python/tree/11.8.x), so ideally we can just fix the lines referencing `libcudart.so.12` to `.11`. But we're transitioning to a new development/release process so let me check with @vzhurba01 later today first, and get back to you later.

**Comment by leofang** [comment]
@Matt711 we discussed and will try to get a new 11.8.x release out next week, with this bug fixed and perhaps also #75 backported.

**Comment by Matt711** [comment]
Thanks @leofang

**Comment by wence-** [comment]
@leofang/@vzhurba01 did this backport/release occur?

**Comment by vzhurba01** [comment]
Not yet. The wheels and conda packages are currently going through pre-release validation. I'll update this issue once posting is complete.

**Comment by vzhurba01** [comment]
>https://pypi.org/project/cuda-python/11.8.4/
>https://anaconda.org/nvidia/cuda-python/files?version=11.8.4

Issue #139 is now complete as both PYPI and Conda (nvidia channel) are now updated with the 11.8.4 patch. Thank you all for your patience.
