### ISSUE TITLE
Figure out how to make docs of `cuda.core` and `cuda.bindings` coexist

### ISSUE THREAD

**Issue by leofang** [NVIDIA/cuda-python#94]
Main question: Do we want to the same project docs with `cuda.core` (#70) & `cuda.bindings` (#75) coexist say under separate tabs or pages, or do we want each namespace package to have their own doc pages (similar to `cuda.{parallel,cooperative}`)?

**Comment by leofang** [comment]
cc: @aterrel in case you have thoughts

**Comment by bryevdv** [comment]
These are separately published / installable packages, is that correct? If so my offhand suggestion is separate docs pages, so that e.g. the PyPI project pages, etc. can have unique landing targets for docs for each.

**Comment by leofang** [comment]
Yes, the intent is to have separate packages (eventually, see #105). I also like the separate page idea. One minor concern I have is if this could cause confusion to the branding, since what I had in mind was that all packages we publish should be considered as components of CUDA Python. It's just that users have the freedom to install only the components that they need.
